package kernbeisser.Windows.EditPriceList;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import java.awt.*;
import javax.swing.*;
import kernbeisser.DBEntities.Article;
import kernbeisser.DBEntities.PriceList;
import kernbeisser.Windows.CollectionView.CollectionController;
import kernbeisser.Windows.CollectionView.CollectionView;
import kernbeisser.Windows.MVC.IView;
import kernbeisser.Windows.MVC.Linked;
import org.jetbrains.annotations.NotNull;

public class EditPriceListView implements IView<EditPriceListController> {

  private JPanel main;
  private CollectionView collectionView;
  private PriceList priceList;

  @Linked private CollectionController<Article> articles;

  @Override
  public void initialize(EditPriceListController controller) {
    priceList = controller.getPricelist();
  }

  @Override
  public @NotNull JComponent getContent() {
    return main;
  }

  private void createUIComponents() {
    collectionView = articles.getView();
  }

  public int confirmChanges(int movedItems, int notListed) {
    String message = "Sollen die Änderungen an der Preisliste gespeichert werden?";
    if (movedItems != 0 || notListed != 0) {
      message += "\nACHTUNG: ";
      if (movedItems != 0) {
        message +=
            movedItems
                + " Artikel "
                + (movedItems == 1 ? "wird" : "werden")
                + "dadurch in eine andere Liste verschoben"
                + (notListed != 0 ? " und" : "");
      }
      if (notListed != 0) {
        message +=
            notListed
                + " Artikel "
                + (notListed == 1 ? "steht" : "stehen")
                + " dann auf keiner Liste mehr";
      }
      message += "!";
    }
    return JOptionPane.showConfirmDialog(
        getContent(),
        message,
        "Änderungen speichern",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE);
  }

  @Override
  public String getTitle() {
    return "Preisliste " + priceList.getName() + "  bearbeiten";
  }

  public void refreshView() {}

  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    main = new JPanel();
    main.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    main.setMaximumSize(new Dimension(-1, -1));
    main.setRequestFocusEnabled(true);
    main.add(
        collectionView.$$$getRootComponent$$$(),
        new GridConstraints(
            0,
            0,
            1,
            1,
            GridConstraints.ANCHOR_CENTER,
            GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
            null,
            null,
            null,
            0,
            false));
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {
    return main;
  }
}
