package kernbeisser.Windows.InventoryMenu;

import com.intellij.uiDesigner.core.GridLayoutManager;
import java.awt.Insets;
import javax.swing.*;
import kernbeisser.Windows.MVC.IView;
import kernbeisser.Windows.MVC.Linked;
import org.jetbrains.annotations.NotNull;

public class InventoryMenuView implements IView<InventoryMenuController> {

  @Linked
  private InventoryMenuController controller;
  private JPanel main;

  @Override
  public void initialize(InventoryMenuController controller) {
  }

  @Override
  public @NotNull JComponent getContent() {
    return main;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    main = new JPanel();
    main.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return main;
  }
}
