package rs.groump;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.CONSTRUCTOR, ElementType.FIELD})
public @interface Key {
  PermissionKey[] value();
  // gets generated by the agent -> the id of the access checking call for tracing back original
  // method
  long id() default 0;
}
