/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kernbeisser.Windows;

import kernbeisser.Finishable;
import kernbeisser.Images;
import kernbeisser.User;

import javax.swing.*;

/**
 *
 * @author julik
 */
public abstract class CashierMenu extends JFrame implements Finishable {

    private User user;

    /**
     * Creates new form CashierMenu
     */
    public CashierMenu(User user) {
        this.user=user;
        initComponents();
        add(new Background(Images.getImage("carrots.png"),this));
        setSize(1070,678);
        setLocationRelativeTo(null);
        setVisible(true);
        addWindowListener(new Finisher(this,this));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addItem = new JButton();
        addUser = new JButton();
        addPriceLists = new JButton();
        startCash = new JButton();
        commingSoon = new JButton();
        back = new JButton();
        editUser = new JButton();
        editItem = new JButton();
        editPriceLists = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        addItem.setText("Artikel Hinzufügen");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        addUser.setText("Nutzer Hinzufügen");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        addPriceLists.setText("Preislisten Hinzufügen");
        addPriceLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPriceListsActionPerformed(evt);
            }
        });

        startCash.setText("Kassieren");
        startCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCashActionPerformed(evt);
            }
        });

        commingSoon.setText("//Coming soon//");

        back.setText("<-Zurück");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        editUser.setText("Nutzer Bearbeiten");
        editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserActionPerformed(evt);
            }
        });

        editItem.setText("Artikel Bearbeiten");
        editItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editItemActionPerformed(evt);
            }
        });

        editPriceLists.setText("Preislisten Bearbeiten");
        editPriceLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPriceListsActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(back)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(commingSoon, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                        .addComponent(startCash, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(addUser, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(addItem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(addPriceLists, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(editUser, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(editItem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(editPriceLists, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                                .addContainerGap(653, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(back)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                                .addComponent(startCash, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(commingSoon, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editUser, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addUser, GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editItem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addItem, GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editPriceLists, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addPriceLists, GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        new AddItems() {
            @Override
            public void finish(JFrame thisWindow) {
                thisWindow.dispose();
                CashierMenu.this.setVisible(true);
            }
        };
        setVisible(false);
    }//GEN-LAST:event_addItemActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        new ManageUser(user.getPermission())   {
            @Override
            public void finish(JFrame thisWindow) {
                thisWindow.dispose();
                CashierMenu.this.setVisible(true);
            }
        };
        setVisible(false);
    }//GEN-LAST:event_addUserActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        finish(this);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserActionPerformed
        new EditUser()   {
            @Override
            public void finish(JFrame thisWindow) {
                thisWindow.dispose();
                CashierMenu.this.setVisible(true);
            }
        };
        setVisible(false);
    }//GEN-LAST:event_editUserActionPerformed

    private void editItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editItemActionPerformed
        new EditItems()  {
            @Override
            public void finish(JFrame thisWindow) {
                thisWindow.dispose();
                CashierMenu.this.setVisible(true);
            }
        };
        setVisible(false);
    }//GEN-LAST:event_editItemActionPerformed

    private void addPriceListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPriceListsActionPerformed
        new ManagePriceLists()  {
            @Override
            public void finish(JFrame thisWindow) {
                thisWindow.dispose();
                CashierMenu.this.setVisible(true);
            }
        };
        setVisible(false);
    }//GEN-LAST:event_addPriceListsActionPerformed

    private void editPriceListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPriceListsActionPerformed
        new EditPriceLists()  {
            @Override
            public void finish(JFrame thisWindow) {
                thisWindow.dispose();
                CashierMenu.this.setVisible(true);
            }
        };
        setVisible(false);
    }//GEN-LAST:event_editPriceListsActionPerformed

    private void startCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startCashActionPerformed
        new Purchase()  {
            @Override
            public void finish(JFrame thisWindow) {
                thisWindow.dispose();
                CashierMenu.this.setVisible(true);
            }
        };
        setVisible(false);
    }//GEN-LAST:event_startCashActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addItem;
    private JButton addPriceLists;
    private JButton addUser;
    private JButton back;
    private JButton commingSoon;
    private JButton editItem;
    private JButton editPriceLists;
    private JButton editUser;
    private JButton startCash;

    // End of variables declaration//GEN-END:variables
}
