/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kernbeisser.Windows;

import kernbeisser.*;

import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.swing.*;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author julik
 */
public class CatalogInput extends JFrame {

    /**
     * Creates new form ItemDataInput
     */
    public CatalogInput() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        data = new JTextArea();
        jLabel1 = new JLabel();
        kkItemData = new JButton();
        progressBar = new JProgressBar();
        importData = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        data.setColumns(20);
        data.setRows(5);
        jScrollPane1.setViewportView(data);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Katalog Aktualiesieren");

        kkItemData.setText("Katalog Aktualiesieren");
        kkItemData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kkItemDataActionPerformed(evt);
            }
        });

        importData.setText("Datei Auswählen");
        importData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importDataActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(importData)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kkItemData)
                        .addGap(32, 32, 32)
                        .addComponent(progressBar, GroupLayout.PREFERRED_SIZE, 509, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 346, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 494, GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(kkItemData)
                        .addComponent(importData))
                    .addComponent(progressBar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void importDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importDataActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if(fileChooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            StringBuilder fileData = new StringBuilder();
            try {
                Files.readAllLines(fileChooser.getSelectedFile().toPath(), StandardCharsets.ISO_8859_1).forEach(e-> fileData.append(e).append("\n"));
            } catch (IOException e) {
                e.printStackTrace();
            }
            data.setText(fileData.toString());
        }

    }//GEN-LAST:event_importDataActionPerformed

    private void kkItemDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kkItemDataActionPerformed
        new Thread(() -> {
            EntityManager em = DBConnection.getEntityManager();
            EntityTransaction et = em.getTransaction();
            ArrayList<ItemKK> catalog = new ArrayList<>();
            progressBar.setMaximum(data.getLineCount());
            et.begin();
            em.createNativeQuery("TRUNCATE catalog").executeUpdate();
            int p = 0;
            for(String line : data.getText().split("\n")) {
                ItemKK item = extractItemKK(line.replace("'", ""));
                if (item != null)
                catalog.add(item);
            }
            HashMap<Integer,Integer> deposit = new HashMap<>();
            catalog.forEach(e -> deposit.put(e.getKkNumber(),e.getNetPrice()));
            for (ItemKK item : catalog) {
                if (item.getSingleDeposit() != 0)
                item.setSingleDeposit(deposit.get(item.getSingleDeposit()));
                if (item.getCrateDeposit() != 0)
                item.setCrateDeposit(deposit.get(item.getCrateDeposit()));
            }
            for (ItemKK kk : catalog) {
                em.persist(kk);
                progressBar.setValue(p++);
            }
            em.flush();
            et.commit();
            em.close();
            progressBar.setValue(data.getLineCount());
            JOptionPane.showMessageDialog(this,"Der KK-Katalog wurde Erfolgreich aktualisiert");
            progressBar.setValue(0);
        }).start();
    }//GEN-LAST:event_kkItemDataActionPerformed

    public static void main(String[] args){
        CatalogInput dataInput = new CatalogInput();
        dataInput.setVisible(true);
    }
    private ItemKK extractItemKK(String line){
        ItemKK item = new ItemKK();
        String[] values = line.split(";");
        try {
            if(values.length<42||values[23].equals("Display")||values[23].equals("Sets"))return null;
            item.setKkNumber(Integer.parseInt(values[0]));
            item.setBarcode(values[4]);
            item.setName(values[6]);
            item.setProducer(values[10]);
            item.setContainerSize(Double.parseDouble(values[22].replaceAll(",", ".")));
            item.setUnit(findUnit(values[23]));
            item.setAmount(extractAmount(values[23].replaceAll("\\D",""),item.getUnit()));
            item.setVatLow(values[33].equals("1"));
            item.setNetPrice((int) Math.round(Double.parseDouble(values[37].replace(",","."))*100));
            if(!values[26].equals(""))item.setSingleDeposit(Integer.parseInt(values[26]));
            if(!values[27].equals(""))item.setCrateDeposit(Integer.parseInt(values[27]));

        }catch (Exception e){
            e.printStackTrace();
            int i = 0;
            for (String value : values) {
                if(value!=null)System.out.print("r:"+i+"["+value+"]");
            }
            System.out.println();
        }
        return item;
    }
    private int extractAmount(String s,Unit u){
        try {
            double d = Double.parseDouble(s.replaceAll(",", "."));
            switch (u) {
                case LITER:
                case KILOGRAM:
                    return (int) (d * 1000);
                case STACK:
                case GRAM:
                case MILLILITER:
                default:
                    return (int) d;
            }
        }catch (NumberFormatException n){
            return extractAmount("1",u);
        }
    }
    private Unit findUnit(String s){
        if(s.toUpperCase().contains("L"))return Unit.LITER;
        else
        if(s.toUpperCase().contains("ML"))return Unit.MILLILITER;
        else
        if(s.toUpperCase().contains("KG"))return Unit.KILOGRAM;
        else
        if(s.toUpperCase().contains("G"))return Unit.GRAM;
        else
            return Unit.STACK;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextArea data;
    private JButton importData;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JButton kkItemData;
    private JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
