package kernbeisser.Windows.PrintLabels;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import jakarta.persistence.NoResultException;
import java.awt.*;
import javax.swing.*;
import kernbeisser.CustomComponents.ObjectTable.ObjectTable;
import kernbeisser.DBEntities.Article;
import kernbeisser.Useful.Tools;
import kernbeisser.Windows.CollectionView.CollectionController;
import kernbeisser.Windows.CollectionView.CollectionView;
import kernbeisser.Windows.MVC.IView;
import kernbeisser.Windows.MVC.Linked;
import org.jetbrains.annotations.NotNull;

public class PrintLabelsView implements IView<PrintLabelsController> {

  private JPanel main;
  private CollectionView collectionView;

  @Linked private CollectionController<Article> articles;

  @Override
  public void initialize(PrintLabelsController controller) {}

  @Override
  public @NotNull JComponent getContent() {
    return main;
  }

  private void createUIComponents() {
    collectionView = articles.getView();
  }

  public boolean confirmChanges() {
    return JOptionPane.showConfirmDialog(
            getContent(),
            "Soll ich mir die ausgewählten Etiketten für den Ausdruck merken?",
            "Später drucken",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE)
        == JOptionPane.YES_OPTION;
  }

  public boolean confirmPrintSuccess() {
    return JOptionPane.showConfirmDialog(
            getContent(),
            "Sollen die gedruckten Etiketten aus der Zusammenstellung entfernt werden?",
            "Etiketten zusammenstellen",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE)
        == JOptionPane.YES_OPTION;
  }

  public void refreshChosenArticle(Article article) {
    articles.getView().getChosen().replace(article, article);
  }

  public void processBarcode(String s) {
    try {
      Article article = PrintLabelsModel.getByBarcode(s);
      CollectionView<Article> articleCollectionView = articles.getView();
      ObjectTable<Article> objectTable = articleCollectionView.getChosen();
      int row = objectTable.getModel().getObjects().indexOf(article);
      if (row == -1) {
        objectTable = articleCollectionView.getAvailable();
        row = objectTable.getModel().getObjects().indexOf(article);
      }
      if (row == -1) return;
      objectTable.selectRow(row);
      objectTable.requestFocusInWindow();
    } catch (NoResultException e) {
      Tools.noArticleFoundForBarcodeWarning(getContent(), s);
    }
  }

  @Override
  public String getTitle() {
    return "Etiketten Zusammenstellen";
  }

  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    main = new JPanel();
    main.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    main.setMaximumSize(new Dimension(-1, -1));
    main.setRequestFocusEnabled(true);
    main.add(
        collectionView.$$$getRootComponent$$$(),
        new GridConstraints(
            0,
            0,
            1,
            1,
            GridConstraints.ANCHOR_CENTER,
            GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
            null,
            null,
            null,
            0,
            false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return main;
  }
}
