/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kernbeisser.Windows.CashierShoppingMask;

import kernbeisser.CustomComponents.Column;
import kernbeisser.CustomComponents.DBTable;
import kernbeisser.CustomComponents.ObjectTable;
import kernbeisser.DBEntitys.User;
import kernbeisser.Windows.*;
import kernbeisser.Windows.ShoppingMask.ShoppingMask;
import kernbeisser.Windows.Window;

import javax.swing.*;
import java.awt.*;
import java.util.Collection;

/**
 *
 * @author julik
 */
public class CashierShoppingMaskView extends Window implements View {
    CashierShoppingMaskController controller;
    private ObjectTable<User> userTable = new ObjectTable<>(
            Column.create("Nachname", User::getSurname),
            Column.create("Vorname", User::getFirstName),
            Column.create("Benutzername", User::getUsername)
    );
    /**
     * Creates new form CashierShoppingMask
     */
    public CashierShoppingMaskView(User seller, Window current) {
        super(current);
        initComponents();
        controller=new CashierShoppingMaskController(seller,this);
        startShopping.setEnabled(false);
        userTable.addSelectionListener((e)->{
            startShopping.setEnabled(true);
            startShopping.setText("Einkauf f\u00fcr "+e.getFirstName()+" "+e.getSurname()+" beginnen");
        });
        userTablePane.add(new JScrollPane(userTable));
        setLocationRelativeTo(null);
        tabbedPane.setFont( new Font( "Dialog", Font.BOLD | Font.ITALIC, 13 ) );
        setVisible(true);
    }

    void openShoppingMask(ShoppingMask mask){
        tabbedPane.addTab("Einkauf f"+'\u00fc'+"r "+mask.getSaleSession().getCustomer().getFirstName(),mask);
    }

    void setUsers(Collection<User> users){
        userTable.setObjects(users);
    }

    @Override
    public Controller getController() {
        return controller;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userTablePane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        startShopping = new javax.swing.JToggleButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbedPane.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Einkauf f\u00fcr jemanden beginnen");

        userTablePane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Benutzer ausw\u00e4hlen:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        userTablePane.setLayout(new java.awt.GridLayout(1, 1));

        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("<- Ladendienst beenden");

        startShopping.setText("Einkauf f\u00fcr x beginnen");
        startShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startShoppingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(userTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 705, Short.MAX_VALUE)
                                                .addComponent(startShopping)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(startShopping))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(userTablePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        tabbedPane.addTab("Hauptseite", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tabbedPane)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startShoppingActionPerformed
        User user = userTable.getSelectedObject();
        try{
            controller.startShoppingFor(user);
        }catch (NullPointerException e){
            startShopping.setEnabled(false);
        }
        tabbedPane.setSelectedIndex(tabbedPane.getTabCount()-1);
    }//GEN-LAST:event_startShoppingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton startShopping;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel userTablePane;

    // End of variables declaration//GEN-END:variables
}
